### ISSUE TITLE
Bug in Content-Length calculation in case of non UTF8 default charset

### ISSUE THREAD

**Issue by lambdaupb** [pippo-java/pippo#519] opened 2019-06-18 11:29 UTC
https://github.com/pippo-java/pippo/blob/cb5ccb453bffcc3cf386adc660674812d10b9726/pippo-core/src/main/java/ro/pippo/core/Response.java#L1096

The content-length is calculated using `String.getBytes()` which uses the system default encoding, then the string is written to the response PrintWriter which always uses `UTF-8`.

If the system uses `latin1` aka ISO8859 then the calculated length does not match the byte length of the UTF-8 output.

I would argue that this is also the wrong place to calculate the Content-Length, especially when sending non-chunked content, the length should be taken from the actual bytes send over the connection.

**Comment by decebals** [comment] 2019-06-18 12:21
Thanks for explanation.  What suggestion do you have?

**Comment by lambdaupb** [comment] 2019-06-18 12:56
For now it would probably suffice if the length is calculated using `.getBytes(StandardCharsets.UTF_8)` as the HttpServletResponse is statically set to `this.httpServletResponse.setCharacterEncoding(StandardCharsets.UTF_8.toString());`

But why use the PrintWriter at all if we can just send the byte array from the length calculation. Currently the string is converted to bytes twice and thrown away the first time after getting the length.
The print writer should really only be used with chunked responses.

**Comment by decebals** [comment] 2019-06-18 13:30
Please create a PR with the solution proposed by you. Thanks!

**Comment by lambdaupb** [comment] 2019-06-18 15:09
Sorry, I don't have the time right now to clone the project and go through the process of creating a pull request.

**Comment by pitschr** [comment] 2019-07-24 15:22
Hi @decebals .

I am facing this issue as well and drove me crazy as it worked on linux / mac / windows (intellij) but not on windows + maven :-) 

The reason was that windows + maven is using the system default charset ( Windows-1252 ) while other approaches used the UTF-8 as the standard. The consequence was that the set of content length using `Response#contentLength(long)` using the `windows-1252` charset, while the data was sent with `utf-8`, became wrong causing throwing `FixedLengthOverflowException` internally in Undertow. In WireShark a truncated JSON was also visible.

As workaround (because pippo is using UTF-8 hardcoded in Response ctor) it should be safe to change from
```contentLength(content.toString().getBytes().length);```
to
```contentLength(content.toString().getBytes(StandardCharsets.UTF_8).length);```
.

My quick experiments also shows that setting of content length is not necessary at all - meaning, the line can be completely removed. But I am not expert in your library I would say that you are the person who knows how to fix it properly.

![image](https://user-images.githubusercontent.com/25742159/61805610-62c42700-ae36-11e9-8437-3df5cbd3e16d.png)

I made a binary change by removing the `contentLength(..)` from `Response` class.

![image](https://user-images.githubusercontent.com/25742159/61805628-68217180-ae36-11e9-9f35-9b0b899131f1.png)


For the rest who are facing the issue as well, make sure that maven surefire is also using UTF-8 per default until the issue is fixed by pippo.
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>.. version here ..</version>
				...
                <configuration>
                    <argLine>-Dfile.encoding=UTF-8</argLine>
                </configuration>
            </plugin>
```

p.s.: if you need

**Comment by lambdaupb** [comment] 2019-07-24 15:33
Maybe it would be helpful to setup errorprone in the project, it detects String.getBytes() and warns about exactly this issue.

https://errorprone.info/bugpattern/DefaultCharset
https://errorprone.info/docs/installation

**Comment by decebals** [comment] 2019-07-24 16:38
@pitschr 
Thanks for detailed explanation. My first instinct says me to remove the line with `contentLength(content.toString().getBytes().length)`. Probably I putted it because I had this information but I see that it generates error and confusion. We will see.

**Comment by whyicantusemyemailasusername** [comment] 2019-07-24 17:00
there is another issue with this part of code - it allocates an array just to calculate string length in bytes. There is no one-liner to fix this though.

**Closed** 2020-04-18 11:36 UTC
